### PR TITLE
Add .gif to README

### PR DESCRIPTION
**Pull request by tsolakoua**
If the .gif is sufficient, we could remove the .png. 

Fixes https://github.com/bblfsh/web/issues/147

### CODE REVIEW

**Comment by bzz** [comment]
There are 2 gifs now in PR, I think we need to keep only one.

Also, even then it's 1.7Mb to download on loading a github page - do you think it is possible to compress it somehow, to make it smaller?

**Comment by tsolakoua** [comment]
In every commit, there are 2 different .gifs, in the oldest commit it's normal speed (seems too slow) and last commit (speed x2, I would keep that one). Sure, I will check out if it's possible to compress it and at the same time not decrease the quality.

**Comment by bzz** [comment]
@tsolakoua thank you for looking into it! I belive we still have to remove un-used gif from this PR, as it will grow the repository size as soon as it's merged.

@dpaz could you please help Anna and take a look if there are any other ways to reduce the size of this gif?

**Comment by dpordomingo** [comment]
I recorded a new screenshot (with my own filter) and it was 600kB
bblfsh web_zoom-out

In case it fits your stands @bzz and @tsolakoua I'd suggest:
- use another screen recorder: I tried `peek` (https://github.com/phw/peek#ubuntu),
- make the screen to be recorder as smaller as possible keeping it meaningfull,
- **reduce recording time**

I think it could be reduced more if it's resized/resampled with Photoshop (but I haven't it)

An alternative could be to capture only the key frames, and prepare the gif animation adding some time interval between frames (ie. using Photoshop).

**Comment by bzz** [comment]
`587 Kb` 🏆 

Thank you so much @tsolakoua @dpordomingo ! 

on 

> I think it could be reduced more if it's resized/resampled with Photoshop (but I haven't it)

@ricardobaeta at a quick glance - would you say it is possible to do that and reduce size even further?

**Comment by dpordomingo** [comment]
@bzz would you agree on merging it until @ricardobaeta could provide a smaller screencast (in case it is even possible).
I think that @tsolakoua proposal is way better than the one we have (even being 580Kb)

**Comment by bzz** [comment]
@dpordomingo  👍 

Merging, if there is no further discussion.

and 🙇🙇🙇 to @tsolakoua for a great improvement!

**Pull request merged**
