### PR TITLE
[WIP] Uast v2

### PR DESCRIPTION
**Pull request by smacker**
Required new uast-viewer with uast2 support.

Currently, there is no libuast for uast2. So the code for filtering on the server is removed.

To produce json I use custom parser. I copy-pasted the default one from sdk and changed it a little.
Maybe sdk can export something to avoid copy-past? //cc @dennwc

### CODE REVIEW

**Comment by dennwc** [comment]
I don't expect IDs to be exposed in the near term via libuast, but I will add a `RawNodes` method to `nodesproto` so you can access them in the server.

**Comment by dennwc** [comment]
Mentioned change was merged as a part of SDK v2.1.0.

**Comment by bzz** [comment]
CI seems to be failing

**Comment by smacker** [comment]
of course it does

**Comment by bzz** [comment]
Care to elaborate why? 

Just FYI https://github.com/bblfsh/client-go/releases/tag/v2.8.7 has `Support XPath queries for UASTv2 (preview)`

**Comment by smacker** [comment]
First of all, you can see in the title the prefix [WIP]. Work in progress means it's not done yet. Obviously, tests should fail on something that isn't ready.

And in more details you can see in the description:

> Required new uast-viewer with uast2 support.

which isn't released

> Currently, there is no libuast for uast2. So the code for filtering on the server is removed.

experimental xpath support for uast2 was added just yesterday.

**Comment by dennwc** [comment]
Hmm, I see that we need to somehow expose node IDs to make the client usable for the Dashboard.

The first option is to project IDs to an `@id` property, but it won't work for arrays.

The second option - we can provide a map from `nodes.UniqueKey` to an ID used in the serialization. I think the second option might be better.

**Comment by dennwc** [comment]
I think exposing the raw data from the serialization was a bad idea after all. We need to find another way of achieving the same result.

**Comment by dennwc** [comment]
Related: https://github.com/bblfsh/bblfshd/pull/199

**Comment by smacker** [comment]
the current approach proved to be not good.

We might use new JSON API from bblfshd if it gets merged or return full tree from our backend.

**Pull request closed without merging**
