### PR TITLE
Upgrade helm deploy to chart version 1.0.0

### PR DESCRIPTION
**Pull request by meyskens**
Signed-off-by: Maartje Eyskens <maartje@eyskens.me>

---
This change is [Reviewable](https://reviewable.io/reviews/bblfsh/web/218)

### CODE REVIEW

**Comment by smacker** [comment]
should I merge?

**Comment by meyskens** [comment]
@smacker we will merge as there are some special steps required from our side

**Comment by driosalido** [comment]
Hi @smacker all the special steps are done. Could you please merge it?

**Comment by smacker** [comment]
done

**Comment by driosalido** [comment]
thanks!

**Pull request merged**
