### PR TITLE
Mode switcher

### LINKED ISSUE #161: select mode for parsing
We have an open PR with support for UAST2 but we are missing a new feature provided by the new client: choose parsing mode.

New bblfsh can return UAST in 3 different formats:
- Semantic (default)
- Annotated
- Native

A user should be able to choose one of them.

We need UI for that.

### PR DESCRIPTION
**Pull request by smacker**
fix #161

based on #164 (3 last commits are new)

screen shot 2018-10-19 at 19 15 29
screen shot 2018-10-19 at 19 15 36

### CODE REVIEW

**Comment by ricardobaeta** [comment]
Hi @smacker Just a little detail: please Capitalise the modes text please.

**Comment by ricardobaeta** [comment]
Hi @smacker Just a little detail: please Capitalise the modes text please.

**Comment by ricardobaeta** [comment]
Hi @smacker Just a little detail: please Capitalise the modes text please.

**Comment by smacker** [comment]
CI is green: https://travis-ci.org/bblfsh/web/builds/443804139

Merging. (So we could test new uast-viewer with different modes)

**Pull request merged**
